### PR TITLE
fix crash of ArrayIndexOutOfBoundsException.

### PR DESCRIPTION
**Pull request by shifujun**
My test.json Crashed. I'm not sure I fix it with right logic, but it works.

[test.zip](https://github.com/airbnb/lottie-android/files/861211/test.zip)

### CODE REVIEW

**Comment by gpeal** [comment]
@shifujun Can you attach the after effects file?

**Comment by gpeal** [comment]
I'd like to know what actually causes this

**Comment by shifujun** [comment]
Here
[testAE.zip](https://github.com/airbnb/lottie-android/files/863533/testAE.zip)

**Comment by gpeal** [comment]
@shifujun You have to save your AE file for bodymovin to pick up gradients. Can you try and re-rendering the json?

**Comment by shifujun** [comment]
@gpeal that Json in test.zip is convert from AE file in testae.zip with bodymovin. I don't understand why you said "have to". Do you mean those json and ae files are not a pair?

This ae test is not my design, I will ask our designer did he changed that ae file after he gave me that json.

Thx.

**Comment by gpeal** [comment]
I'm saying that I was able to export them fine. Unlike most properties, you have to save your changes in After Effects before exporting or they won't get picked up. I'm guessing that's what happened to your designer. I don't think this change is necessary.

[Banners.zip](https://github.com/airbnb/lottie-android/files/865278/Banners.zip)

**Comment by shifujun** [comment]
@gpeal sorry for my little AE knowledge. In another word, do you mean the array.length() is alway divided evenly by 4? If that's true, I suggest check that and throw a runtimeexception for a bad json reason.

**Comment by gpeal** [comment]
@shifujun Yes, the array should always be divisible by 4 and it is when I export your animation with bodymovin.

**Comment by gpeal** [comment]
@shifujun Are you okay with me closing this PR?

**Comment by shifujun** [comment]
👍👌

**Pull request closed without merging**
