### PR TITLE
3.0.7 Revert AndroidX to Support

### PR DESCRIPTION
**Pull request by gentrio**
#1234 make a branch from 3.0.7 and revert the androidx migration

### CODE REVIEW

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/1224912c6a5d735a)**

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/1807668aded571e9)**

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/d166417fb56c0ac7)**

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/464bdf26a7bfaa04)**

**Comment by gentrio** [comment]
> **[Snapshots Failed](https://app.bitrise.io/build/464bdf26a7bfaa04)**

@gpeal can't pass the bitrise because the Runner Test Class is androidX AndroidJUnitRunner.

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/e8dbffeffb9f6d79)**

**Comment by gentrio** [comment]
@gpeal  can't pass the bitrise because the bitrise.yml inst_test_runner_class AndroidJUnitRunner under package AndroidX

**Comment by gpeal** [comment]
I'm actually going to hold off on this and do a 3.1.0-support when it comes out (soon).

**Pull request closed without merging**
