### PR TITLE
Two value animator fixes

### LINKED ISSUE #663: setting new values for setMinAndMaxProgress in onAnimationEnd, new animation segment is not starting
I have a json that contains different "segments" for serveral states of the app. On certain states, I have to play different segments after each other. I ensured, that `loop` is always false, if there is a follow up animation. However, with the code example below (simplified), the very first animation runs fine, but the next animation segment doesn't show. The `AnimatorListener.onAnimationStart()` is called for the new segment, but it doesn't show on the screen. I cannot post the json file, because it's under NDA. But it is working without any problems on iOS. Am I missing something?
 
    override fun onResume() {
        super.onResume()
        setupAndStartAnimation(0f, 0.09f)
    }

    fun setupAndStartAnimation(start: Float, end: Float, loop: Boolean = false)
        animation_view.cancelAnimation() //also tried with .pauseAnimation()
        animation_view.setMinAndMaxProgress(start, end)
        if (loop) {
            animation_view.repeatCount = LottieDrawable.INFINITE
        } else {
            animation_view.repeatCount = 0
        }
        animation_view.removeAllAnimatorListeners()
        animation_view.addAnimatorListener(object : Animator.AnimatorListener {
            override fun onAnimationStart(animator: Animator) { /* no-op */ }
            override fun onAnimationRepeat(animator: Animator) { /* no-op */ }
            override fun onAnimationCancel(animator: Animator) { /* no-op */ }

            override fun onAnimationEnd(animator: Animator) {
                setupAndStartAnimation(0.14f, 0.29f, true)
            }
        })
        animation_view.playAnimation() // also tried with resumeAnimation()

### LINKED ISSUE #703: Setting min and max progress doesn't respect start frame and crashes
#628 **setProgres going to wrong frame when startFrame > 0** fixed only the setProgress function but not related setMinProgress, setMaxProgress and setMinAndMaxProgress setters.

This results in a crash when you try to use, e.g. setProgress(0.5f):
`java.lang.IllegalStateException: Frame must be [71,000000,23,000000]. It is 23,000000
at com.airbnb.lottie.utils.LottieValueAnimator.verifyFrame(LottieValueAnimator.java:230)
at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:112)`

### PR DESCRIPTION
**Pull request by gpeal**
* Take into account start and end frames for min and max progress
* Remove the frame callback before notifying the end listeners so that if they start an animation, the notification frame will not be removed.
Fixes #703 
Fixes #663

### CODE REVIEW

**Comment by gpeal** [comment]
Snapshot Test Results: https://happo.io/compare?q=lottie-master-android26..lottie-115d56dc87efccaa8fb14ac9a64ebe292085517c-android26&a=4

**Comment by gpeal** [comment]
Snapshot Test Results: https://happo.io/compare?q=lottie-master-android26..lottie-a3f8a8584ffbe32217c026ee8f09f4dc58363277-android26&a=4

**Comment by gpeal** [comment]
Snapshot Test Results: https://happo.io/compare?q=lottie-master-android26..lottie-80afbf54b7e9d0cc970775b62b5087898e5c9a66-android26&a=4

**Comment by headsvk** [comment]
@gpeal good job but you are missing a fix for one method - setMinAndMaxProgress()

**Pull request merged**
