### PR TITLE
Fixed danglign choreographer callback.

### PR DESCRIPTION
**Pull request by dryganets**
**This patch fixes the performance issue.**

I've seen the cases where the previous version of the code was re-adding callbacks to the choreographer in case of cancelation/pause. Now it is designed to make it impossible. It looks like there is a copy of the callbacks stored somewhere in the stack. I've been able to reproduce the problem on Android 6.0 and 7.0.

This issue caused application performance degradation and battery drain in the background for us.

### CODE REVIEW

**Comment by dryganets** [comment]
I agree. I've seen similar issues in other projects I worked on already.

For Lottie I've done following:
1. Put temporary asserts in all control methods to make sure everything running on UI thread.
2. Set the breakpoints to the control methods to make sure that the flow is correct.

Assertions didn't trigger, app flow looks reasonable to me, but animations never stop spinning.

My perception: this is a natural system level issue.

I looked in the code of Choreographer in android SDK - everything looked sane to me and synchronized correctly there, but I didn't look deep inside of the C++ implementation part.

Apparently, there is another thread involved as this is a vsync callbacks from the screen.

**Will try to make a sample app to see if the problem will happen there.**

**Comment by dryganets** [comment]
There is no way to repro it in the sample app ...
Will take a more detailed look at the issue I was able to repro in our app later.

**Comment by gpeal** [comment]
@dryganets Got it. So do you recommend holding off for now?

**Comment by dryganets** [comment]
As for the fix, it should be safe to apply, and we verified that it fixes the problem.
I didn't manage to repro it on mine device though so that might be device specific problem.
On Wednesday I'll get the device where we had a repro, then I could tell for sure.

**Comment by dryganets** [comment]
Hi @gpeal, I reproduced the issue. **Feel free to merge this PR. It fixes the bug. The Lottie flow looks correct except `running` usage.**
This is not device specific and reproduces on skype code base if this patch is reverted.

We are using react-native, and whole react-native rendering sub-system relies heavily on the Choreographer callbacks, it looks like it contributes to the race condition.
In fact, react-native uses choreographer callbacks so heavily that it has to throttle itself :)

I added the logs in postFrameCallback and removeFrameCallback methods to track the execution flow.

See fragment of the log with my comments:

```
### Play animation call. Remove old callback
05-23 16:17:03.202 11286 11286 I XXX     : removeFrameCallback  isRunning: false #197560867
05-23 16:17:03.202 11286 11286 I XXX     : java.lang.RuntimeException
05-23 16:17:03.202 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.removeFrameCallback(LottieValueAnimator.java:236)
05-23 16:17:03.202 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.postFrameCallback(LottieValueAnimator.java:226)
05-23 16:17:03.202 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.playAnimation(LottieValueAnimator.java:177)
05-23 16:17:03.202 11286 11286 I XXX     : 	at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:346)
### Play animation call. Post callback
05-23 16:17:03.203 11286 11286 I XXX     : wasRunning: false postFrameCallback #197560867
05-23 16:17:03.203 11286 11286 I XXX     : java.lang.RuntimeException
05-23 16:17:03.203 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.postFrameCallback(LottieValueAnimator.java:228)
05-23 16:17:03.203 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.playAnimation(LottieValueAnimator.java:177)
### running callback one time
05-23 16:17:04.867 11286 11286 I XXX     : doFrame #197560867

### View detached from the UI and animation canceled				
05-23 16:17:04.956 11286 11286 I XXX     : removeFrameCallback  isRunning: true #197560867
05-23 16:17:04.956 11286 11286 I XXX     : java.lang.RuntimeException
05-23 16:17:04.956 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.removeFrameCallback(LottieValueAnimator.java:236)
05-23 16:17:04.956 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.cancel(LottieValueAnimator.java:201)

### doFrame callback which is supposed to be removed runs again
05-23 16:17:04.960 11286 11286 I XXX     : removeFrameCallback  isRunning: false #197560867
05-23 16:17:04.960 11286 11286 I XXX     : java.lang.RuntimeException
05-23 16:17:04.960 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.removeFrameCallback(LottieValueAnimator.java:236)
05-23 16:17:04.960 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.postFrameCallback(LottieValueAnimator.java:226)
05-23 16:17:04.960 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:85)

05-23 16:17:04.960 11286 11286 I XXX     : wasRunning: false postFrameCallback #197560867
05-23 16:17:04.960 11286 11286 I XXX     : java.lang.RuntimeException
05-23 16:17:04.960 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.postFrameCallback(LottieValueAnimator.java:228)
05-23 16:17:04.960 11286 11286 I XXX     : 	at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:85)

### Keep running
05-23 16:17:06.722 11286 11286 I XXX     : doFrame #197560867
05-23 16:17:08.428 11286 11286 I XXX     : doFrame #197560867
05-23 16:17:10.116 11286 11286 I XXX     : doFrame #197560867
```


I'm ignoring the logs from doFrame unless isRunning == false.
All other flows produce logs in remove and post callback methods.
Exception is used to see the stack trace of the call.

This is my changes in case you are curious.

```
  protected void postFrameCallback(boolean log) {

    boolean wasRunning = isRunning;
    log = log || !wasRunning;
    removeFrameCallback(log);
    if (log) {
      Log.i("XXX",  "wasRunning: " + wasRunning + " postFrameCallback #" + this.hashCode(), new RuntimeException());
    }
    Choreographer.getInstance().postFrameCallback(this);
    isRunning = true;
  }

  protected void removeFrameCallback(boolean log) {
    if (log) {
      Log.i("XXX", "removeFrameCallback " + " isRunning: " + isRunning + " #" + this.hashCode(), new RuntimeException());
    }
    Choreographer.getInstance().removeFrameCallback(this);
    isRunning = false;
  }

@Override public void doFrame(long frameTimeNanos) {
    throtler++;
    if (throtler % 100 == 0) {
      Log.i("XXX", "doFrame " + this.hashCode());
    }

....

```

**Pull request merged**
