### PR TITLE
Adding Titanium module

### PR DESCRIPTION
**Pull request by m1ga**
Added a link to the Titanium Android module for Lottie

### CODE REVIEW

**Comment by gpeal** [comment]
Can you rebase your change?

**Comment by m1ga** [comment]
Thanks! The Titanium iOS module version will be at the same repo soon. We are merging the two projects

**Comment by gpeal** [comment]
@m1ga great! Can you file a PR against it when it's done?

**Comment by m1ga** [comment]
Yes, will do that!

**Comment by m1ga** [comment]
Module is now supporting both version and I've created a PR here https://github.com/airbnb/lottie-ios/pull/77
since all of the community plugins support iOS they all can be added there

**Comment by hansemannn** [comment]
iOS is now included 🚀

**Pull request merged**
