### PR TITLE
Added the ability to change properties dynamically

### PR DESCRIPTION
**Pull request by gpeal**
## Change Summary
This PR allows you to update specific properties in an animation at runtime.
This PR is a breaking change because it replaces the color filter functionality added in #207 with this more flexible system.

#441 #443 

Full documentation available [here](http://airbnb.io/lottie/android/dynamic.html).

## TODO
- [ ] Update the dynamic properties demo fragment.
- [ ] Investigate a recursive and non-recursive trailing wildcard. Potentially `**` or `r`
This is the current demo but I'm working on a better one:
dynamic

### CODE REVIEW

**Comment by gpeal** [comment]
Fyi @hzsweers @handstandsam @seanfchan @rhysdavis @thenickreynolds

**Comment by hzsweers** [comment]
oooo awesome!

**Comment by handstandsam** [comment]
The best keeps getting better! Awesome work!

**Comment by seanfchan** [comment]
great!

**Comment by brianchu** [comment]
Pulling gpeal--update-value branch compile, run but crash compiling missing ASquares.json file.

**Comment by gpeal** [comment]
@brianchu Try a build clean. It is there.

**Pull request closed without merging**
