### PR TITLE
Use film strip snapshots rather than individual progress points

### PR DESCRIPTION
**Pull request by gpeal**

### CODE REVIEW

**Comment by gpeal** [comment]
Snapshot Test Results: https://happo.io/compare?q=lottie-master-android26..lottie-beb0f1da9a1dc6f71f543ebcbf1ef75681f42b18-android26&a=27

**Comment by gpeal** [comment]
**Snapshot Tests**
Report: https://happo.io/a/27/report/fce181071c1f94e992e3744c8469ac0de60c34b8-android26
Diff: https://happo.io/a/27/compare/master-android26/fce181071c1f94e992e3744c8469ac0de60c34b8-android26

**Comment by gpeal** [comment]
**Snapshot Tests**
Report: https://happo.io/a/27/report/4e59f158be29be61b9dd076b89c79f89a65f2ad5-android26
Diff: https://happo.io/a/27/compare/master-android26/4e59f158be29be61b9dd076b89c79f89a65f2ad5-android26

**Comment by gpeal** [comment]
**Snapshot Tests**
Report: https://happo.io/a/27/report/70800eedee101d148aba2827968eaab2e7dfdafc-android26
Diff: https://happo.io/a/27/compare/master-android26/70800eedee101d148aba2827968eaab2e7dfdafc-android26

**Comment by gpeal** [comment]
**Snapshot Tests**
Report: https://happo.io/a/27/report/8624983e470697ef6796fa6cfa1a4a1368be3ed0-android26
Diff: https://happo.io/a/27/compare/master-android26/8624983e470697ef6796fa6cfa1a4a1368be3ed0-android26

**Comment by gpeal** [comment]
**Snapshot Tests**
Report: https://happo.io/a/27/report/0f869f96ba71d177b9f49a9fffcc656851839c2d-android26
Diff: https://happo.io/a/27/compare/master-android26/0f869f96ba71d177b9f49a9fffcc656851839c2d-android26

**Comment by gpeal** [comment]
**Snapshot Tests**
Report: https://happo.io/a/27/report/02b15cbe509e9ac513e2241274ee13bae07e914d-android26
Diff: https://happo.io/a/27/compare/master-android26/02b15cbe509e9ac513e2241274ee13bae07e914d-android26

**Comment by gpeal** [comment]
**Snapshot Tests**
Report: https://happo.io/a/27/report/939a11b0a7425815e4668ec07b83871e9aa0b552-android26
Diff: https://happo.io/a/27/compare/master-android26/939a11b0a7425815e4668ec07b83871e9aa0b552-android26

**Review by Jellybean228 — COMMENTED** [review]
I think mine is broke please make normal

**Pull request merged**
