### PR TITLE
Use moshi implementation for json parsing

### PR DESCRIPTION
**Pull request by gpeal**
There's a dependency on OKIO & 8 classes copied from Moshi. Need to figure out best path forward. Ideally we don't depend on all of Moshi but still get the gains of the new JsonReader & Options api. This should fix the random Android 8 crashes.

### Performance
I ran the snapshot tests with ~1800 animations and summed up just the parsing time. The old parsing code took 13,145ms and 13,645ms on each test run (avg 13,395ms). The new code took 12,858ms each time. There aren't enough trials to deduce statistical differences but if these numbers hold, the new code parses ~5% faster.
It does reduce memory allocations during parsing which may contribute to the performance improvement.

I'm leaning on merging this to hopefully fix https://github.com/airbnb/lottie-android/issues/667

fyi: @digitalbuddha

### CODE REVIEW

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/a98315dfe3a31ec2)**

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/0c1d386c2a29bfd0)**

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/02ff21f72f85d84c7df31737397a5aca4b732f7e-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/02ff21f72f85d84c7df31737397a5aca4b732f7e-android28)

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/2dc3560a714fc485a0864bb3b0e4d15c3d6dbfbe-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/2dc3560a714fc485a0864bb3b0e4d15c3d6dbfbe-android28)

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/2dc3560a714fc485a0864bb3b0e4d15c3d6dbfbe-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/2dc3560a714fc485a0864bb3b0e4d15c3d6dbfbe-android28)

**Comment by hfrsoussama** [comment]
Can we have this bug fix on a non AndroidX version of Lottie please (ex 2.7.x)

**Comment by gpeal** [comment]
@hfrsoussama I made a 3.0.3-support version but it takes a lot of manual work and I'm not sure I'm going to do it again. Maybe I'll do one more but if you want to make a branch from 3.0.7 and revert the androidx migration and make a PR, I can publish it.

**Pull request merged**
