### PR TITLE
Add support for rendering fonts and dynamic text

### PR DESCRIPTION
**Pull request by gpeal**
This support builds on text glyph support by supporting rendering custom fonts as well as custom text through a text delegate. This enables Lottie to be used with translations as well as interactive animations.

All text operations such as fills, strokes, tracking, etc are supported by this.

dynamic-text

#173
#349
#350
#352

### CODE REVIEW

**Comment by Antiblanks** [comment]
Hey Gabriel we made a start on a iOS/Android project a few months ago where we looked at using Lottie but sidestepped it because of the lack of dynamic text support at the time. We're about to pickup that same project again and have noticed you guys have turned some attention to this more recently. Can you tell me where you are with this now both for iOS and Android and what your roadmap is for improving this feature? I need to decide whether to continue with the custom route we were going down or consider using Lottie again. If you are going to be supporting soon then what restrictions are there on using text, particularly effects with text; more basic stuff like animating drop shadows, glows etc to more complex stuff like morphing the shapes of letters. Let me know if you get the chance... Thanks in advance.

**Comment by gpeal** [comment]
@Antiblanks I added basic text support on Android. You can find a list of supported features [here](http://airbnb.io/lottie/supported-features.html). You can also use a TextDelegate to do custom text.

iOS doesn't support text yet. You can file/search for an issue there for more info.

**Comment by jalopez1986** [comment]
@gpeal How r u?, For when can you have support for this feature in ios?

**Comment by gpeal** [comment]
@jalopez1986 It is on the roadmap.

**Pull request merged**
