### PR TITLE
Move to using only ALL_SAVE_FLAG with Canvas.saveLayer API

### PR DESCRIPTION
**Pull request by sorotokin**
Before opening a pull request:

* If you added a new feature or fixed a bug, add a json file to assets/Tests and add a test 
for it in `LottieTest#testAll`.
* Run screenshot tests by running `./gradlew --daemon recordMode screenshotTests` on a Nexus 
5 5.1.0 emulator and commit all screenshots that have changed.
* Assign gpeal as a reviewer.

### CODE REVIEW

**Comment by sorotokin** [comment]
Not sure how to do shapshots, recordMode screenshotTests are not available gradle tasks. com.facebook.testing.screenshot:plugin seemed to be removed back in December, could not figure out how to use it.

**Comment by gpeal** [comment]
@sorotokin I don't think this is correct. We still want to use the save flags for older APIs for performance reasons but want to use the flagless version for >= 0. I recommend making a helper function like saveLayerCompat(rect, paint) that passes the flags in for < 0.

Don't worry about the tests. I need to update the template.

**Comment by gpeal** [comment]
@sorotokin ^

**Comment by sorotokin** [comment]
I did a bit of a research to determine what version should be used to determine what is "old" API is. Starting with SDK version 22, documentation explicitly suggests using ALL_SAVE_FLAG for performance reasons.
1. Should I use that version?
2. Is it even worth going back to version 22 (Android 5.1)?

**Comment by gpeal** [comment]
@sorotokin Yes, Lottie supports 16+

**Comment by Curwer** [comment]
Any news on this? We will start targeting android p now that the final api is released.

**Comment by gpeal** [comment]
I'll merge this if the correct save flags are used pre-P. Otherwise I'll do this myself in the next few weeks.

**Comment by sorotokin** [comment]
I am working at re-submitting this today. Sorry for the delay; github is just not my native environment.

**Comment by sorotokin** [comment]
@gpeal, please take another look

**Comment by PaulWoitaschek** [comment]
This broke all my animations on Lollipop

**Comment by sorotokin** [comment]
Sorry for this; I think I broke it in #748

Could you try merging #824 and see if it fixes the problem? I do not have L
handy.

Peter

**Pull request merged**
