### PR TITLE
Map gradient stroke start and end points for the parent matrix

### PR DESCRIPTION
**Pull request by gpeal**
Fixes the second half of #1188 
@Moes81

### CODE REVIEW

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/fadc4317cad5945f)**

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/8f144a1f7ddd1ad9)**

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/39cca3eaf95909a6)**

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/faab6f8deabef1eae86afcf9478cdc8d4b64894b-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/faab6f8deabef1eae86afcf9478cdc8d4b64894b-android28)

**Comment by Moes81** [comment]
@gpeal Thanks for this PR! I checked it, and at least the weird stroke bug is gone. 
A side effect is, that the different colors while the "h" is wobling, get noticeably darker and completely loose the turquise color. I'm a little worried that this might introduce a regression on previously working animations.
What do you think about it? Would you like to take care of the colors within this branch?

**Comment by gpeal** [comment]
@Moes81 Yes, they showed up in the snapshot diffs above. I won't merge this until they are resolved.

**Comment by Moes81** [comment]
Hey @gpeal !
Any progress here? I guess, there are more crucial things to do right now?

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/374a0d04f347bc74)**

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/16c01e309760257a5f9b944498256c69b917252a-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/16c01e309760257a5f9b944498256c69b917252a-android28)

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/387cdab530b171eea68a15bde8e166eb81fd9b68-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/387cdab530b171eea68a15bde8e166eb81fd9b68-android28)

**Comment by gpeal** [comment]
Closing in favor of #1333

**Pull request closed without merging**
