### PR TITLE
Added memory cache layer for async network requests

### PR DESCRIPTION
**Pull request by RhysDavis**
Added a call to the LRU Memory cache for lottie network requests.

I've also removed the asyncFetch calls from the NetworkFetcher since the url lottie composition creates an Async task from the LRU cache call

### CODE REVIEW

**Comment by gpeal** [comment]
@RhysDavis Can you test this?

**Comment by elihart** [comment]
Is this new code any different from what `fromZipStream` does? if that works with bitmaps and caching then it seems loading from url would be the same.

Can we also update `LottieAnimationView#setAnimationFromUrl` to use `LottieCompositionCache`, similar to what `setAnimation` does, so that we get an in memory cache for the url animation once it is loaded?

**Comment by Gnod** [comment]
@elihart we can't use like that, the problem it quiet the same as I mention above. As the bitmap might be recycle when the view is detach from the view, ImageAssetManager#bitmapForId currently can't measure that we can get bitmap again.  As the setAnimation is use a resource with image from the imagesFolder,  the ImageAssetManager#bitmapForId has the logic to get the bitmap back from the imagesFolder.

**Comment by RhysDavis** [comment]
@elihart `LottieAnimationView#setAnimationFromUrl` does go through the composite cache, I don't pass a `cacheKey` since I generate one based on the URL that's being loaded.  ie `LottieAnimationView#setAnimationFromUrl` calls `LottieCompositeFactory#fromUrl` directly which will hit the animation cache.

@Gnod if what you're saying is true, wouldn't the cache implementation be broken for all methods of loading a lottie file? The cache implementation isn't exclusive for network urls

**Comment by Gnod** [comment]
@RhysDavis the other logic is ok as the ImageAssetManager#bitmapForId method had logic to load the bitmap from imagesFolder we set. But if the image is from network, currently logic will not find the image and load it as a bitmap again if the origin bitmap had been recycled.

**Comment by gpeal** [comment]
Fyi #1002

**Comment by gpeal** [comment]
Fixes #978

**Pull request merged**
