### PR TITLE
Fixes #51 : Locked screen orientation to portrait

### LINKED ISSUE #51: Letters disappears on changing the screen orientation in FontActivity of Sample App
Currently when the screen orientation is changed then the letters written disappears.

Expected that letters should not disappears on changing the orientation. :)

### PR DESCRIPTION
**Pull request by saketkumar95**
Fixes https://github.com/airbnb/lottie-android/issues/51  Screen is locked to portrait :) 

@gpeal Have a look. :)

### CODE REVIEW

**Comment by pdenise708** [comment]
Scream stays locked in portrait

**Comment by pdenise708** [comment]
Scream stays locked in portrait

**Comment by gpeal** [comment]
@saketkumar95 Can you go ahead and just lock the entire app to portrait? I don't see any need for landscape anywhere.

**Comment by saketkumar95** [comment]
@gpeal Yeah sure.. :)

**Comment by saketkumar95** [comment]
@gpeal Done,  Review now! :)

**Pull request merged**
