### PR TITLE
Add unit test for XML initialized Lottie view.

### PR DESCRIPTION
**Pull request by boduan402**
To prevent issue like https://github.com/airbnb/lottie-android/issues/1432 from happening again, add a unit test to verify the Lottie view initialization process via XML.

One nit of this PR is the XML test file is included in aar. If there's better option to exclude it from release package, please advise.

### CODE REVIEW

**Comment by gpeal** [comment]
@boduan402 CI runs `"./gradlew lintRelease testReleaseUnitTest"` so you could add this to the LottieSample codebase and it would run on CI.

**Comment by boduan402** [comment]
> @boduan402 CI runs `"./gradlew lintRelease testReleaseUnitTest"` so you could add this to the LottieSample codebase and it would run on CI.

Cool, great idea. Let me take a look in next a few days.

**Comment by gpeal** [comment]
@boduan402 Are you still planning on finishing this?

**Comment by boduan402** [comment]
yes, I will finish it in 1~2 weeks. Was on something else recently :)

**Pull request merged**
