### PR TITLE
fixed: Using Text Delegate and scaletype then the textfield wont posi…

### PR DESCRIPTION
**Pull request by pikaMouse**
I had the same issue as #1310. When I use TextDelegate to change the text in my animation and I use a scaletype for example "Center" then the textfield doesn't respect the scaling & positioning of the LottieAnimationView.At present，I've fixed it with using "concat" rather than "setMatrix" before draw something in the canvas. The difference between them as follow：
* setMatrix:Completely replace the current matrix with the specified matrix.
* concat:Preconcat the current matrix with the specified matrix

### CODE REVIEW

**Comment by mgod** [comment]
This fixed some text layout issues I was having as well. If we get this or a similar PR passing on the master branch, is it likely to get merged?

**Comment by pikaMouse** [comment]
> This fixed some text layout issues I was having as well. If we get this or a similar PR passing on the master branch, is it likely to get merged?

I try it

**Comment by mgod** [comment]
@pikaMouse I hope you don't mind, I included this commit along with some other dynamic text layout fixes in PR #1635

**Comment by pikaMouse** [comment]
> @pikaMouse I hope you don't mind, I included this commit along with some other dynamic text layout fixes in PR #1635

Of course not

**Pull request closed without merging**
