### PR TITLE
Apply left/top bounds before scaling

### PR DESCRIPTION
**Pull request by qhyuan**
Should move the image to the right place before scaling it.

### CODE REVIEW

**Review by gpeal — COMMENTED** [review]
Can you add some context and an example of something that was broken before but working correctly now?

**Comment by qhyuan** [comment]
@gpeal 
[sample-debug.apk.zip](https://github.com/user-attachments/files/17470941/sample-debug.apk.zip)
image

Here is my code, you can add it to PreviewFragment to reproduce this issue. Thank you!
```
package com.airbnb.lottie.samples.views

import android.content.Context
import android.util.AttributeSet
import android.view.ViewGroup
import android.widget.LinearLayout
import androidx.appcompat.widget.AppCompatSeekBar
import com.airbnb.epoxy.ModelView
import com.airbnb.lottie.LottieCompositionFactory
import com.airbnb.lottie.LottieDrawable
import com.airbnb.lottie.samples.R

@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
class SeekBarExample @JvmOverloads constructor(context: Context?, attrs: AttributeSet? = null, defStyleAttr: Int = 0) :
    LinearLayout(context, attrs, defStyleAttr) {

    private val thumbLottieDrawable = object : LottieDrawable() {
        override fun getIntrinsicWidth(): Int {
            return 100
        }

        override fun getIntrinsicHeight(): Int {
            return 100
        }
    }

    init {
        orientation = VERTICAL
        val seekBar = AppCompatSeekBar(requireNotNull(context))
        addView(seekBar, LayoutParams(LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT))

        LottieCompositionFactory.fromRawRes(context, R.raw.bullseye)
            .addListener {
                thumbLottieDrawable.composition = it
                seekBar.thumb = thumbLottieDrawable
                thumbLottieDrawable.playAnimation()
            }
    }
}
```
企业微信截图_14813724-a8d5-46ef-9b92-5125f1121963

**Comment by gpeal** [comment]
Could you add a unit test or snapshot test that would catch this?

**Review by gpeal — APPROVED** [review]
Checked other transforms and we do preTranslate before preScale in other places so this is likely correct. 🤞

**Pull request merged**
