### PR TITLE
Fix AnimatorPauseListener callbacks

### PR DESCRIPTION
**Pull request by Viacheslav01**
LottieValueAnimator doesn't utilize a base implementation of pause and resume methods of Animator.
The result is undispatched events to AnimatorPauseListener.

### CODE REVIEW

**Comment by Viacheslav01** [comment]
How can I run snapshot-tests correctly?

**Comment by gpeal** [comment]
It won't work locally without the api key either 🤔 I just changed how CI works (to make it faster) but will need to think about how to best handle this.

**Comment by Viacheslav01** [comment]
Is this PR has a chance to be merged?

**Comment by gpeal** [comment]
Could you try updating this branch from master? The snapshot tests should work now.

**Review by gpeal — APPROVED** [review]

**Comment by gpeal** [comment]
Thanks for adding this!

**Review by gpeal — COMMENTED** [review]
Actually, before landing this, could you add the APIs to LottieDrawable and LottieAnimationView (with javadocs) just like the other listeners?

https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java#L844

**Comment by Viacheslav01** [comment]
It was implemented in PR https://github.com/airbnb/lottie-android/commit/70fe2f89fa118045fdade501c289bd6182742ee9 but it didn't work properly without a correct listeners handling.

**Pull request merged**
