### PR TITLE
 A thought ------- Let Lottie Support expressions

### PR DESCRIPTION
**Pull request by VipMinF**
Lottie have no more function for AE， but we can get developers to develop it。
I tried to extend this module，first，Replace PoinF with CPointF , create class MagiPoint extend CPointF

qq 20170223205826
qq 20170223205857
qq 20170223205951

............Unable to upload images

### CODE REVIEW

**Comment by gpeal** [comment]
@VipMinF Thanks for looking in to this! I'm going to pull this down and play around with it.
Do you mind if I make a few changes and push it back to this PR?

**Comment by VipMinF** [comment]
Not at all. I’ll be happy to

**Comment by gpeal** [comment]
@VipMinF I took a look through your  PR.
I'd like to work towards a longer term solution for expressions rather than just doing pattern matching.

If you'd like to add wiggle support on its own, that would be a good place to start.
You'll want to rebase though. There have been major architectural changes for 2.0 since your fork.

**Comment by VipMinF** [comment]
image
image

in the bodymovin.js file ，it uses the eval function to execute the expression. If you do not want to use the match, we can try using the ScriptEngineManager

**Comment by gpeal** [comment]
@VipMinF bodymovin.js is a javascript player itself so it can directly execute expressions from After Effects. However, there is not trivial way afaik to do this from native Java on Android. Do you know of reasonable way to handle this?

**Comment by VipMinF** [comment]
AE scripts and expressions are based on the JavaScript programming language. If you want to explain this expression, I think there are only two options: 1 using JDK6 provided after ScriptEngineManager. 2 we write our own interpreter.

**Comment by gpeal** [comment]
@VipMinF Correct. If you'd like to explore options to get js expressions working in a generic fashion, that would be great. I'm not sure if there will be a trivial way though.

**Comment by gpeal** [comment]
@VipMinF Feel free to add Wiggle support (outside of expressions) if you would like though.

**Comment by sepehr1014** [comment]
Any updates on this matter?

**Comment by gpeal** [comment]
@sepehr1014  None yet.

**Pull request closed without merging**
