### PR TITLE
Allow animations in zip files to include base64 encoded inline images

### PR DESCRIPTION
**Pull request by hepenghui168**
… json is base64, the images are empty and the lottie cannot be displayed normally

### CODE REVIEW

**Comment by hepenghui168** [comment]
> Could you zip [this file](https://github.com/airbnb/lottie-android/blob/master/sample-compose/src/main/res/raw/we_accept_inline_image.json) and put it in the same folder? That will add a snapshot test for this to make sure it works and doesn't break in the future.

**Comment by hepenghui168** [comment]
> Could you zip [this file](https://github.com/airbnb/lottie-android/blob/master/sample-compose/src/main/res/raw/we_accept_inline_image.json) and put it in the same folder? That will add a snapshot test for this to make sure it works and doesn't break in the future.

https://g.alicdn.com/eva-assets/74c9b7fb0ef80de7f67d70a435952858/0.0.1/tmp/87fb874/eb0fbd23-bb60-43d3-9f3f-0d8fbc9f8921.zip

**Comment by hepenghui168** [comment]
> Could you zip [this file](https://github.com/airbnb/lottie-android/blob/master/sample-compose/src/main/res/raw/we_accept_inline_image.json) and put it in the same folder? That will add a snapshot test for this to make sure it works and doesn't break in the future.

I passed the test, can I merge into the master branch?

**Comment by gpeal** [comment]
You will need to actually add the zip file [here](https://github.com/airbnb/lottie-android/tree/master/snapshot-tests/src/main/assets/Tests) on your branch and call it `ZipInlineImage.zip` so that it shows up in the snapshot tests. If itw works, the snapshot bot diff will show one new snapshot.

**Comment by hepenghui168** [comment]
> You will need to actually add the zip file [here](https://github.com/airbnb/lottie-android/tree/master/snapshot-tests/src/main/assets/Tests) on your branch and call it `ZipInlineImage.zip` so that it shows up in the snapshot tests. If itw works, the snapshot bot diff will show one new snapshot.

I have added ZipInlineImage.zip, the self-test passed, when will there be results?

**Review by gpeal — APPROVED** [review]
I'll look into why the snapshot didn't show up in the report but thanks for your contribution.

**Comment by hepenghui168** [comment]
> I'll look into why the snapshot didn't show up in the report but thanks for your contribution.

I'm also happy to contribute to lottie-android.

**Pull request merged**
