### PR TITLE
Fix setMinAndMaxFrames

### PR DESCRIPTION
**Pull request by Kevinrob**
`public void setMinAndMaxFrames(int minFrame, int maxFrame)` started to behave strange when I updated. So I debug it. I found something very (very) strange.

If `composition` is `null`, `compositionMinFrame` will be set to `Float.MIN_VALUE`.  
And if I pass to the function `minFrame = 0` then... (attach your belt...)

`MiscUtils.clamp(minFrame, compositionMinFrame, compositionMaxFrame)`
=> `MiscUtils.clamp(0, Float.MIN_VALUE, Float.MAX_VALUE)`
**give `1.4E-45` (ouch!)**

... I don't know exactly why but `(Float.MIN_VALUE >= 0) == true`!
It's probably because the float are cast to `int`.

Anyway, elsewhere we use `Integer.MIN_VALUE` and `Integer.MAX_VALUE` for `this.minFrame` and `this.maxFrame` 👍 

capture

### CODE REVIEW

**Comment by Kevinrob** [comment]
@gpeal 👋 Can you review my PR please 😃

**Comment by gpeal** [comment]
@Kevinrob Oh wow, this is interesting. Per [this](https://stackoverflow.com/a/11420190/715633) SO post, I think the correct thing to do is to use `-Float.MAX_VALUE`

**Comment by Kevinrob** [comment]
@gpeal I just read the SO post and... 😯! So, you are right, here, it's `-Float.MAX_VALUE` that we want!

**Comment by gpeal** [comment]
Naming is hard 😛

**Pull request merged**
