### PR TITLE
radius, size & position value callbacks for rectangle

### PR DESCRIPTION
**Pull request by digitalbuddha**
I'll fix formatting in next push

### CODE REVIEW

**Comment by gpeal** [comment]
**[Snapshots Failed](https://app.bitrise.io/build/f2889a55aca1226a)**

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/de23d6a64e22ef6dc226963825e0863adf7bb97e-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/de23d6a64e22ef6dc226963825e0863adf7bb97e-android28)

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/de23d6a64e22ef6dc226963825e0863adf7bb97e-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/de23d6a64e22ef6dc226963825e0863adf7bb97e-android28)

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/f9f30ee64d1c69f72ea3c3f3885267157775de32-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/f9f30ee64d1c69f72ea3c3f3885267157775de32-android28)

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/0a7b9f46a31dd20ffb2c17db8c66efb2c0b4c554-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/0a7b9f46a31dd20ffb2c17db8c66efb2c0b4c554-android28)

**Comment by digitalbuddha** [comment]
Confirmed that size property is now functioning correctly.  Let me know if anything else is need here

**Comment by digitalbuddha** [comment]
formatting reverted.  Fixes https://github.com/airbnb/lottie-android/issues/894

**Comment by gpeal** [comment]
**Snapshot Tests**
**28**: [Report](https://happo.io/a/27/report/637ee67f09e5488c094081bf6a297e34845fe7aa-android28) [Diff](https://happo.io/a/27/p/27/compare/master-android28/637ee67f09e5488c094081bf6a297e34845fe7aa-android28)

**Pull request merged**
