### PR TITLE
Add a LottieAnimationView overload for ZipInputStream

### LINKED ISSUE #2409: Support load dotlottie for setAnimation(InputStream)
https://github.com/airbnb/lottie-android/blob/4c805889968bfa2eba6c87cd99a093aa5261beb3/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L507-L518

Currently it looks like only support json, can we add support for zip?

I'm using this as workaround for now:

```kt
val stream = FileInputStream(File(filepath))
val result = LottieCompositionFactory.fromZipStreamSync(ZipInputStream(stream), filepath.hashCode().toString())
val composition = result.value ?: throw IllegalStateException("Unable to parse ${filepath}")
view.setComposition(composition)
```

Also, change from `fromZipStreamSync` to `fromZipStream` can be complex, maybe make `view.setCompositionTask` public will be better.

### PR DESCRIPTION
**Pull request by gpeal**
Closes #2409

### CODE REVIEW

**Comment by thevoiceless** [comment]
Thanks @gpeal ! Any idea when this will be released?

**Comment by gpeal** [comment]
I'll cut a new release in the next week or two.

**Comment by thevoiceless** [comment]
Gotcha, thanks! Are you also in charge of `lottie-react-native` releases? Only asking because that's where I actually need this functionality 😅

**Comment by gpeal** [comment]
@thevoiceless Nope! I delegated lottie-react-native a few years ago.

**Comment by thevoiceless** [comment]
@gpeal Any update on a release? `lottie-react-native` just did one

**Pull request merged**
