### PR TITLE
Update to Compose Beta 02

### PR DESCRIPTION
**Pull request by jossiwolf**
Hia, some small updates!

### CODE REVIEW

**Review by gpeal — APPROVED** [review]

**Comment by gpeal** [comment]
@jossiwolf It looks like you have a failing unit test here

**Comment by jossiwolf** [comment]
Yeah, thanks! Looking into it, the failure looks a bit weird...

**Comment by jossiwolf** [comment]
Let's hold back on merging the PR until there's an update on this issue, looks like Chris already reported it: https://issuetracker.google.com/issues/182468430

**Comment by gpeal** [comment]
@jossiwolf Thanks for finding this issue. It's a frustrating one because it's tied to AGP which is hard coded to the Android Studio canaries...

**Comment by gpeal** [comment]
@jossiwolf For now, can you downgrade agp to get the build to go green (even if it doesn't run locally in Android Studio)?

**Comment by jossiwolf** [comment]
@gpeal Yeah sounds good! We can still upgrade locally and not commit it.

**Comment by jossiwolf** [comment]
@gpeal Looks like we're good on CI here! Will make a PR for AGP 7.0.0-alpha09 once the Robolectric issue is resolved :)

**Pull request merged**
